"""add source_documents content_text

Revision ID: 032d7b5db861
Revises: 3e4cdbfaa597
Create Date: 2026-08-27 01:54:30.577749

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '032d7b5db861'
down_revision = '3e4cdbfaa597'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('content_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'content_text')
    # ### end Alembic commands ###
