"""add variant last_verified_at

Revision ID: 2874a915c30c
Revises: 81fbaea6f4a4
Create Date: 2026-08-27 02:22:21.877898

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2874a915c30c'
down_revision = '81fbaea6f4a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_variants', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_variants', 'last_verified_at')
    # ### end Alembic commands ###
