"""add series price_range_note

Revision ID: 39f2a9a52f6a
Revises: cd4ceebca72c
Create Date: 2026-08-29 17:05:48.427952

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '39f2a9a52f6a'
down_revision = 'cd4ceebca72c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_series', sa.Column('price_range_note', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_series', 'price_range_note')
    # ### end Alembic commands ###
