"""initial schema

Revision ID: 3e4cdbfaa597
Revises: 
Create Date: 2026-08-27 01:16:03.392923

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3e4cdbfaa597'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_owner_id'), 'comparisons', ['owner_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('verified_status', sa.String(length=24), nullable=False),
    sa.Column('credibility', sa.String(length=16), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('parent_company', sa.String(length=120), nullable=True),
    sa.Column('brand_type', sa.String(length=32), nullable=False),
    sa.Column('consumer_sales', sa.Boolean(), nullable=False),
    sa.Column('official_site', sa.String(length=500), nullable=True),
    sa.Column('active_status', sa.String(length=16), nullable=False),
    sa.Column('inclusion_reason', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_brand_type'), 'brands', ['brand_type'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('data_quality_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('value_a', sa.String(length=500), nullable=True),
    sa.Column('value_b', sa.String(length=500), nullable=True),
    sa.Column('source_a_id', sa.Integer(), nullable=True),
    sa.Column('source_b_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_a_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['source_b_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_conflicts_entity_id'), 'data_quality_conflicts', ['entity_id'], unique=False)
    op.create_table('vehicle_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('body_type', sa.String(length=16), nullable=True),
    sa.Column('positioning', sa.String(length=120), nullable=True),
    sa.Column('energy_types', sa.JSON(), nullable=False),
    sa.Column('official_page_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('active_status', sa.String(length=16), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_series_brand_id'), 'vehicle_series', ['brand_id'], unique=False)
    op.create_index(op.f('ix_vehicle_series_name'), 'vehicle_series', ['name'], unique=False)
    op.create_table('monthly_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('sales_type', sa.String(length=16), nullable=False),
    sa.Column('sales_count', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['vehicle_series.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'month', 'sales_type', name='uq_sales_series_month_type')
    )
    op.create_index(op.f('ix_monthly_sales_series_id'), 'monthly_sales', ['series_id'], unique=False)
    op.create_table('vehicle_model_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('year_name', sa.String(length=40), nullable=False),
    sa.Column('launch_status', sa.String(length=24), nullable=False),
    sa.Column('launched_at', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['vehicle_series.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'year_name', name='uq_model_year_series_year')
    )
    op.create_index(op.f('ix_vehicle_model_years_series_id'), 'vehicle_model_years', ['series_id'], unique=False)
    op.create_table('vehicle_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('model_year_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('config_version', sa.String(length=120), nullable=False),
    sa.Column('powertrain', sa.String(length=80), nullable=False),
    sa.Column('drivetrain', sa.String(length=40), nullable=False),
    sa.Column('package', sa.String(length=120), nullable=True),
    sa.Column('energy_type', sa.String(length=16), nullable=False),
    sa.Column('body_type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sales_regions', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_year_id'], ['vehicle_model_years.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['vehicle_series.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'model_year_id', 'config_version', 'powertrain', 'drivetrain', 'effective_from', name='uq_variant_business_key')
    )
    op.create_index('ix_variants_series_status', 'vehicle_variants', ['series_id', 'status'], unique=False)
    op.create_index(op.f('ix_vehicle_variants_energy_type'), 'vehicle_variants', ['energy_type'], unique=False)
    op.create_index(op.f('ix_vehicle_variants_model_year_id'), 'vehicle_variants', ['model_year_id'], unique=False)
    op.create_index(op.f('ix_vehicle_variants_series_id'), 'vehicle_variants', ['series_id'], unique=False)
    op.create_table('comparison_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['vehicle_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_id', 'variant_id', name='uq_comparison_item_variant')
    )
    op.create_index(op.f('ix_comparison_items_comparison_id'), 'comparison_items', ['comparison_id'], unique=False)
    op.create_index(op.f('ix_comparison_items_variant_id'), 'comparison_items', ['variant_id'], unique=False)
    op.create_table('official_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('price_cny', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['vehicle_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_prices_variant_id'), 'official_prices', ['variant_id'], unique=False)
    op.create_index('ix_prices_variant_current', 'official_prices', ['variant_id', 'effective_to'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('model_year_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('page_or_section', sa.String(length=120), nullable=True),
    sa.Column('raw_object_path', sa.String(length=500), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('credibility', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['model_year_id'], ['vehicle_model_years.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['vehicle_series.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['vehicle_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_brand_id'), 'source_documents', ['brand_id'], unique=False)
    op.create_index(op.f('ix_source_documents_series_id'), 'source_documents', ['series_id'], unique=False)
    op.create_table('spec_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('fact_key', sa.String(length=80), nullable=False),
    sa.Column('fact_value', sa.String(length=240), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('cycle', sa.String(length=16), nullable=True),
    sa.Column('page_or_section', sa.String(length=80), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['vehicle_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spec_facts_variant_category', 'spec_facts', ['variant_id', 'category'], unique=False)
    op.create_index(op.f('ix_spec_facts_variant_id'), 'spec_facts', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spec_facts_variant_id'), table_name='spec_facts')
    op.drop_index('ix_spec_facts_variant_category', table_name='spec_facts')
    op.drop_table('spec_facts')
    op.drop_index(op.f('ix_source_documents_series_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_brand_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index('ix_prices_variant_current', table_name='official_prices')
    op.drop_index(op.f('ix_official_prices_variant_id'), table_name='official_prices')
    op.drop_table('official_prices')
    op.drop_index(op.f('ix_comparison_items_variant_id'), table_name='comparison_items')
    op.drop_index(op.f('ix_comparison_items_comparison_id'), table_name='comparison_items')
    op.drop_table('comparison_items')
    op.drop_index(op.f('ix_vehicle_variants_series_id'), table_name='vehicle_variants')
    op.drop_index(op.f('ix_vehicle_variants_model_year_id'), table_name='vehicle_variants')
    op.drop_index(op.f('ix_vehicle_variants_energy_type'), table_name='vehicle_variants')
    op.drop_index('ix_variants_series_status', table_name='vehicle_variants')
    op.drop_table('vehicle_variants')
    op.drop_index(op.f('ix_vehicle_model_years_series_id'), table_name='vehicle_model_years')
    op.drop_table('vehicle_model_years')
    op.drop_index(op.f('ix_monthly_sales_series_id'), table_name='monthly_sales')
    op.drop_table('monthly_sales')
    op.drop_index(op.f('ix_vehicle_series_name'), table_name='vehicle_series')
    op.drop_index(op.f('ix_vehicle_series_brand_id'), table_name='vehicle_series')
    op.drop_table('vehicle_series')
    op.drop_index(op.f('ix_data_quality_conflicts_entity_id'), table_name='data_quality_conflicts')
    op.drop_table('data_quality_conflicts')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_brand_type'), table_name='brands')
    op.drop_table('brands')
    op.drop_table('sources')
    op.drop_index(op.f('ix_comparisons_owner_id'), table_name='comparisons')
    op.drop_table('comparisons')
    # ### end Alembic commands ###
