"""widen_spec_fact_value

Revision ID: 7e9dda19f6df
Revises: 39f2a9a52f6a
Create Date: 2026-08-29 19:17:21.389269

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '7e9dda19f6df'
down_revision = '39f2a9a52f6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spec_facts', 'fact_value',
               existing_type=sa.VARCHAR(length=240),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spec_facts', 'fact_value',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=240),
               existing_nullable=True)
    # ### end Alembic commands ###
