"""add external series refs

Revision ID: cd4ceebca72c
Revises: 2874a915c30c
Create Date: 2026-08-29 01:15:47.905771

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'cd4ceebca72c'
down_revision = '2874a915c30c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_series_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['vehicle_series.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_external_ref_source_external')
    )
    op.create_index(op.f('ix_external_series_refs_external_id'), 'external_series_refs', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_series_refs_series_id'), 'external_series_refs', ['series_id'], unique=False)
    op.create_index(op.f('ix_external_series_refs_source_id'), 'external_series_refs', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_series_refs_source_id'), table_name='external_series_refs')
    op.drop_index(op.f('ix_external_series_refs_series_id'), table_name='external_series_refs')
    op.drop_index(op.f('ix_external_series_refs_external_id'), table_name='external_series_refs')
    op.drop_table('external_series_refs')
    # ### end Alembic commands ###
